# Uncomment this line to define a global platform for your project
 platform :ios, '9.0'

target 'WhatsAppClone' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!


 pod 'Firebase'
 pod 'Firebase/Auth'
 pod 'Firebase/Database'
 pod 'Firebase/Storage'
 pod 'JSQMessagesViewController'
 pod 'JSQSystemSoundPlayer'
 pod 'FBSDKCoreKit'
 pod 'FBSDKLoginKit'
 pod 'FBSDKShareKit'
 pod 'GoogleSignIn'
 pod 'Fabric'
 pod 'TwitterKit'
  # Pods for WhatsAppClone

end
